# Generated by Django 2.1.2 on 2019-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('publish', models.CharField(max_length=256)),
                ('publish_year', models.CharField(max_length=256)),
                ('score', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='imgs')),
                ('kind', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=256)),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256)),
                ('buyer', models.IntegerField()),
                ('seller', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('count_product', models.IntegerField()),
                ('money', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=256)),
                ('seller', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('permission', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
