# Generated by Django 2.1.2 on 2019-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='book_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='buyer',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='count_product',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='money',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='seller',
            field=models.CharField(max_length=256),
        ),
    ]
